Support for Requester Pays
skyplane-project/skyplane pull request #520
Opened 2022-09-06 22:50 UTC by HaileyJang

Skyplane CLI will now take in additional flag to support requester pays bucket. Requester-pays bucket are buckets that charges the person who downloads the objects. More information in the following link: https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysBuckets.html

2022-09-06 23:28 UTC, parasj requested changes
Great work, this will really help our users! I added some minor comments to improve maintainability with a single code path for both workflows.

2022-09-06 23:28 UTC, parasj commented on skyplane/chunk.py
> +    src_requester_pays: str = ''
We should move this to the gateway startup code as a flag

2022-09-06 23:28 UTC, parasj commented on skyplane/cli/cli.py
> +    requester_pays: str = typer.Option(None, "--requester-pays", help = "Bucket flag for Requester pays buckets")
We should make this a config flag in config.py and make this a boolean flag

2022-09-06 23:28 UTC, parasj commented on skyplane/cli/cli_impl/cp_replicate.py
> +        source_iface.requester_pays = True
Actually, add a method like `set_requester_pays()` to `ObjectStoreInterface` with abstract methods (silently do nothing for GCP and Azure).

2022-09-06 23:28 UTC, parasj commented on skyplane/cli/cli_impl/cp_replicate.py
> +    with console.status(f"Querying objects in {source_bucket}\n") as status:
Print the new line with the logger statement `logger.error("Specified object does not exist.")`

2022-09-06 23:28 UTC, parasj commented on skyplane/cli/cli_impl/cp_replicate.py
> +    requester_pays: str = '',
Use a bool for this

2022-09-06 23:28 UTC, parasj commented on skyplane/obj_store/s3_interface.py
> +            try:
Do this for everything, not just requester pays

2022-09-06 23:28 UTC, parasj commented on skyplane/obj_store/s3_interface.py
> +            try:
Add a limit = 1 for this call

2022-09-06 23:28 UTC, parasj commented on skyplane/obj_store/s3_interface.py
> +        if not self.requester_pays:
You should be able to set the RequesterPays using this method: https://stackoverflow.com/a/44376294

2022-09-13 16:24 UTC, parasj approved these changes
This looks good. Also update the error message here to note that the user may need to enable requester pays:
https://github.com/skyplane-project/skyplane/blob/0d875bd3cbf6a32345eca3624af30c870d46c8ab/skyplane/exceptions.py#L7-L11

`Please ensure that the bucket exists and is accessible. See https://skyplane.org/en/latest/faq.html#i-am-unable-to-copy-files-to-a-folder-in-my-destination-bucket-due-to-a-missing-object-error.```
For that documentation page, you should add more text to elaborate on requester pays setup.

2022-09-13 16:24 UTC, parasj commented on skyplane/obj_store/object_store_interface.py
> +    def activate_requester(self):
`activate_requester ` => `set_requester_pays_mode(status: bool)` so we can disable it as well

2022-09-13 16:24 UTC, parasj commented on skyplane/obj_store/s3_interface.py
> +                s3_client.list_objects(Bucket=self.bucket_name, RequestPayer="requester", MaxKeys=1)
Merge these cases as:
```python
requester_pays = {"RequestPayer": "requester"} if self.requester_pays else {}
s3_client.list_objects(Bucket=self.bucket_name, MaxKeys=1, **requester_pays)
```

2022-09-13 16:24 UTC, parasj commented on skyplane/obj_store/s3_interface.py
> +        if self.requester_pays:
Merge as above

2022-09-13 16:24 UTC, parasj commented on skyplane/obj_store/s3_interface.py
> +                s3_client.list_objects(Bucket=self.bucket_name, RequestPayer="requester", MaxKeys=1)
This will let us add other args for S3 options in the future as well

2022-09-13 22:00 UTC, HaileyJang commented
FAQ changes made in #538

2022-09-13 23:10 UTC, parasj approved these changes

2022-09-14 05:37 UTC, merged