Skyplane API Design
skyplane-project/skyplane pull request #591
Opened 2022-10-02 22:27 UTC by JasonDing0401

A draft implementation of Skyplane API that continues from #568.

2022-10-13 08:26 UTC, JasonDing0401 commented
The API for **simple copy** should be ready for review (demo is in `skyplane/skyplane/demo.py`). Notice that right now the client only takes a pre-configured config file (`auth=None`). Next, we will update with: 1. load auth from our customized auth class; 2. multiple copies within a session.

2022-10-14 00:44 UTC, parasj requested changes
@abiswal2001 and I synced over Zoom over some requested changes in the API

2022-10-14 00:44 UTC, parasj commented on skyplane/demo.py
> +client1 = new_client(None)
Fix `__init__.py` so this can be:
```python
client = Skyplane.client()
status = client.copy(...)
```

2022-10-14 00:44 UTC, parasj commented on skyplane/api/auth/auth.py
> +class Auth:
Push these as arguments directly in the functions

2022-10-14 00:44 UTC, parasj commented on skyplane/api/auth/auth_config.py
> +    def __init__(self, client_id: str, subscription_id: str, umi_id: str, umi_name: str, resource_group: str):
Change order of these so:
* subscription_id is first
* resource_group has default or is second
* prefix client_id with umi_

2022-10-14 00:44 UTC, parasj commented on skyplane/api/api.py
> +async def cp(
Make a folder: `api/impl/cp_simple.py` and move this there. Do not expose it via `__init__.py`

2022-10-14 00:44 UTC, parasj commented on skyplane/api/api.py
> +def deprovision():
Move to `api/impl/deprovision.py`

2022-10-14 00:44 UTC, parasj commented on skyplane/api/api.py
> +            if config_default_flags.get("verify_checksums"):
Exceptions should be raised directly without catching them, and content shouldn't be printed out for API calls

2022-10-14 00:44 UTC, parasj commented on skyplane/api/api.py
> +async def cp(
Make this synchronous for the simple API

2022-11-02 02:27 UTC, parasj commented
@ShishirPatil is creating a Sky Camp repo. We should push the notebook to that repo and then close this PR.

2022-11-02 02:52 UTC, ShishirPatil commented
Repository now lives here: `https://github.com/skyplane-project/skyplane-tutorial`

2022-11-02 02:56 UTC, JasonDing0401 commented
Thank you @ShishirPatil! I will push the notebook tonight and close this PR.

2022-11-02 04:34 UTC, closed without merging